name: Window

on: [push]

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 30
    
    
    steps:
    - name: Download other tools
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://public-cdn.cloud.unity3d.com/hub/prod/UnityHubSetup.exe -OutFile UnityHubSetup.exe
        curl -L -o "$env:USERPROFILE\Desktop\gitpush.bat" "https://www.dropbox.com/scl/fi/4yzfc96vrbaklc9o23zzh/backup.bat?rlkey=6rtbjt401ldkj7s2n9o71cuo4&st=geq8jblj&dl=0"
        curl -L -o "login_to_unity.ps1" "https://www.dropbox.com/scl/fi/q1w3fu3tzcrkrxcbplz62/login_to_unity.ps1?rlkey=4q5ir7hb4qld5pkl628x5jpxl&st=3x01wc65&dl=0"
        curl -L -o "gitsetup.ps1" "https://www.dropbox.com/scl/fi/tbq7km1oztjfncr1fmq8j/gitsetup.ps1?rlkey=r2vhfl5765bwcfukp4p72efeq&st=3updqo6c&dl=0"
        git clone https://github.com/CipherSyntax1/Flappy-Bird.git
        
        
    - name: Extract ngrok
      run: Expand-Archive ngrok.zip

    - name: Auth with ngrok
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable Terminal Services
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

    - name: Install Unity Hub
      run: Start-Process -FilePath ".\UnityHubSetup.exe" -ArgumentList "/S" -Wait

    - name: Run login_to_unity.ps1
      run: |
        powershell.exe -File login_to_unity.ps1
      shell: powershell
      
    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp 3389
