name: Window

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Download
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://public-cdn.cloud.unity3d.com/hub/prod/UnityHubSetup.exe -OutFile UnityHubSetup.exe
        curl -L -o "$env:USERPROFILE\Desktop\gitpush.bat" "https://www.dropbox.com/scl/fi/7kkg03wkpvpvmbliud11d/gitpush.bat?rlkey=h4ae0pnlyblmyxsm89i7t480z&st=wcwyohth&dl=0"
        curl -L -o "$env:USERPROFILE\Desktop\setup.py" "https://www.dropbox.com/scl/fi/2v1omsp0vl2dqv86ay7rp/Unity.bat.txt?rlkey=gikb2um61bgq8ui1h6nnh8yvx&st=ula8ndgj&dl=0"
    - name: Extract
      run: Expand-Archive ngrok.zip
    - name: Auth
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - name: Install Unity Hub
      run: Start-Process -FilePath ".\UnityHubSetup.exe" -ArgumentList "/S" -Wait
    
    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp 3389
